export const BILL_LIST_REQUEST = 'BILL_LIST_REQUEST';
export const BILL_LIST_SUCCESS = 'BILL_LIST_SUCCESS';
export const BILL_LIST_FAIL = 'BILL_LIST_FAIL';

export const BILL_DETAILS_REQUEST = 'BILL_DETAILS_REQUEST';
export const BILL_DETAILS_SUCCESS = 'BILL_DETAILS_SUCCESS';
export const BILL_DETAILS_FAIL = 'BILL_DETAILS_FAIL';

export const BILL_CREATE_REQUEST = 'BILL_CREATE_REQUEST';
export const BILL_CREATE_SUCCESS = 'BILL_CREATE_SUCCESS';
export const BILL_CREATE_FAIL = 'BILL_CREATE_FAIL';
export const BILL_CREATE_RESET = 'BILL_CREATE_RESET';

export const BILL_UPDATE_REQUEST = 'BILL_UPDATE_REQUEST';
export const BILL_UPDATE_SUCCESS = 'BILL_UPDATE_SUCCESS';
export const BILL_UPDATE_FAIL = 'BILL_UPDATE_FAIL';
export const BILL_UPDATE_RESET = 'BILL_UPDATE_RESET';

export const BILL_DATE_REQUEST = 'BILL_DATE_REQUEST';
export const BILL_DATE_SUCCESS = 'BILL_DATE_SUCCESS';
export const BILL_DATE_FAIL = 'BILL_DATE_FAIL';